Sprint1/step2
ysemenyuk/react-burger pull request #2
Opened 2021-08-20 07:50 UTC by ysemenyuk

2021-08-20 08:32 UTC, SmilingJey requested changes
Здравствуйте!

Хорошая работа, проект полность соответвует макету, реализовано открытие попапов через портал, но есть несколько замечаний в реализации функционала:

**Основные места, которые нужно исправить:**

- добавьте проверку ответа сервера - res.ok

- перенесите itemDataPropTypes.js в корень src или utils, этот файл не должен быть в components

- для всех необходимых для отображения компонента пропсов в propTypes должен задаваться `.isRequired`, проверьте во всех компонентах

- управляйте видимостью попапа в самом месте, где он подключается {visible && (.........)}

- перенесите фильтрацию в компонент BurgerIngredients

- у Modal и ModalOverlay не описаны  propTypes

**Болеее подробно замечания и места, в которых можно улучшить проект, так же описаны в коде:**

2021-08-20 08:32 UTC, SmilingJey commented on src/api/routes.js
> +export const ingridientsRoute = 'https://norma.nomoreparties.space/api/ingredients';
**Можно лучше**
вынесите только базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2021-08-20 08:32 UTC, SmilingJey commented on src/components/App/App.js
> +        .then((res) => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2021-08-20 08:32 UTC, SmilingJey commented on src/components/App/App.js
> +    function getData(url) {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2021-08-20 08:32 UTC, SmilingJey commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
> +      <Modal visible={visible} header='Детали ингредиента' onClose={handleCloseModal}>
**Надо исправить**

обычно принято делать проверку на открытие модального окна не в Modal (if (!visible) return null;), а здесь и если оно не открыто, то вообще не рендерить компонент

```
      {visible && (<Modal header='Детали ингредиента' onClose={handleCloseModal}>
        <IngredientDetails item={item} />
      </Modal>)}
```


**Можно лучше**

перенесите модальное окно в BurgerIngredients, ну нужно 3 модальных окна для каждой группы

2021-08-20 08:32 UTC, SmilingJey commented on src/components/BurgerConstructor/BurgerConstructor.js
> +      <Modal visible={visible} onClose={handleCloseModal}>
**Надо исправить**

обычно принято делать проверку на открытие модального окна не в Modal (if (!visible) return null;), а здесь и если оно не открыто, то вообще не рендерить компонент

```
      {visible && (<Modal onClose={handleCloseModal}>
        <OrderDetails />
      </Modal>)}
```

2021-08-20 08:32 UTC, SmilingJey commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
>            .filter((item) => item.type === props.type)
**Надо исправить**

перенесите фильтрацию в компонент BurgerIngredients, а сюда передавайте только нужные ингредиенты и как пропс заголовок категории

Выполняйте фильтрацию не в jsx, а заранее

Например:

```
const buns = useMemo(data.filter((item) => item.type === 'buns'), [data]);
const sauces= useMemo(data.filter((item) => item.type === 'sauce'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);

return (
   ....................
      <div className={styles.itemsBox}>
        <ItemsGroup data={buns} title={'Булки'} />
        <ItemsGroup data={sauces} title={'Соусы'} />
        <ItemsGroup data={mains } title={'Начинки'} />
      </div>
   ..................
)
```

2021-08-20 08:32 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.js
>          <Tab value='one' active={true}>
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
[https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView](https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView)

2021-08-20 08:32 UTC, SmilingJey commented on src/components/Modal/Modal.js
> +
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2021-08-20 08:32 UTC, SmilingJey commented on src/components/Modal/Modal.js
> +    <>
**Можно лучше**
эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```
<>
  <div>.....</div>
  <div>.....</div>
</>

```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2021-08-20 08:32 UTC, SmilingJey commented on src/components/Modal/ModalOverlay/ModalOverlay.js
> +
**Надо испарвить**

для этого компонента так же нужно описать PropTypes

2021-08-21 23:48 UTC, ysemenyuk commented on src/components/BurgerIngredients/BurgerIngredients.js
>          <Tab value='one' active={true}>
сделал так, так как при scrollIntoView скролл всей странице тоже перемещается
```
  const setCurrent = (tab) => {
    setCurrentTab(tab);
    const target = document.getElementById(tab);
    if (target && target.parentNode) {
      // target.scrollIntoView({ behavior: 'smooth' });
      target.parentNode.scrollTo({
        top: target.offsetTop - target.parentNode.offsetTop,
        behavior: 'smooth',
      });
    }
  };
```

2021-08-21 23:52 UTC, ysemenyuk commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
>            .filter((item) => item.type === props.type)
почему нельзя в самом элементе IncridientsGroup фильтровать?
чтоб не писать три функции рядом
```
  const ingridientsGroup = React.useMemo(
    () => ingridients.filter((item) => item.type === type),
    [ingridients, type]
  );
```
ведь зависимость все равно полный массив ingridients

2021-08-22 00:22 UTC, ysemenyuk commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
>            .filter((item) => item.type === props.type)
тогда можно было бы сделать так
```
  const groups = [
    { type: 'bun', title: 'Булки' },
    { type: 'sauce', title: 'Соусы' },
    { type: 'main', title: 'Начинки' },
  ];

      <ul className={styles.itemsList}>
        {groups.map(({ type, title }) => (
          <li>
            <IngridientsGroup
              ingridients={ingridients}
              anchor={type}
              title={title}
              handleOpenModal={handleOpenModal}
            />
          </li>
        ))}
      </ul>
```

и табы также замапить

2021-08-22 08:34 UTC, SmilingJey commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
>            .filter((item) => item.type === props.type)
> почему нельзя в самом элементе IncridientsGroup фильтровать

IncridientsGroup  должен знать только о данных, которые он должен отобразить, не нужно передавать в него все данные и он сам сортирует

>  табы также замапить
табы при желании можно так же замапить

2021-08-22 08:36 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.js
>          <Tab value='one' active={true}>
рабочее решение, но лучше сделать, что бы страница вписывалась в высоту браузера и высота списка ингредиентов подстраивалась под неё, тогда на странице не появится скрола

2021-08-22 09:19 UTC, ysemenyuk commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
>            .filter((item) => item.type === props.type)
примерно так норм?

```
  const data = React.useMemo(
    () =>
      ingridients.reduce((acc, item) => {
        if (!acc[item.type]) acc[item.type] = [];
        acc[item.type].push(item);
        return acc;
      }, {}),
    [ingridients]
  );
  
  const groups = [
    { type: 'bun', title: 'Булки', items: data['bun'] },
    { type: 'sauce', title: 'Соусы', items: data['sauce'] },
    { type: 'main', title: 'Начинки', items: data['main'] },
  ];

      <ul className={styles.itemsList}>
        {groups.map(({ type, title, ingridients }) => (
          <li key={type}>
            <IngridientsGroup
              items={items}
              anchor={type}
              title={title}
              handleOpenModal={handleOpenModal}
            />
          </li>
        ))}
      </ul>
```

2021-08-22 15:19 UTC, SmilingJey commented on src/components/BurgerIngredients/ItemsGroup/ItemsGroup.js
>            .filter((item) => item.type === props.type)
да, хорошее решение

2021-08-23 07:15 UTC, SmilingJey approved these changes
Вы отлично поработали над проектом, замечания исправлены

Успехов в дальнейшем обучении!

2021-08-27 00:25 UTC, merged